version: "3.9"

services:

  db:
    image: mysql:8
    container_name: hungryhub_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hungryhub_development
      MYSQL_USER: hungryhub
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7
    container_name: hungryhub_redis
    ports:
      - "6380:6379"

  app:
    build: .
    container_name: hungryhub_api
    command: bash -c "bundle install && rails s -b 0.0.0.0"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    environment:
      DATABASE_HOST: db
      DATABASE_USER: hungryhub
      DATABASE_PASSWORD: password

volumes:
  mysql_data: