version: "3.9"

services:

  mysql:
    image: mysql:8
    container_name: restaurant_mysql
    command: --mysql-native-password=ON
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: restaurant_development
      MYSQL_USER: restaurant
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7
    container_name: restaurant_redis
    ports:
      - "6380:6379"

volumes:
  mysql_data: