default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: 5
  username: restaurant
  password: password
  host: 127.0.0.1
  port: 3307

development:
  <<: *default
  database: restaurant_development

test:
  <<: *default
  database: restaurant_test